CREATE TABLE "user" (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    ip VARCHAR(39) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    bounce_count INT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_user_email ON "user" (email);
CREATE TABLE code (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    "value" VARCHAR(64) NOT NULL,
    user_id INT,
    PRIMARY KEY (id),
    UNIQUE ("value"),
    FOREIGN KEY(user_id) REFERENCES "user" (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX ukey_code_user_id ON code (user_id) EXCLUDE NULL KEYS;
