CREATE TABLE "user"
(
    ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    EMAIL VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    IP VARCHAR(39) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);
CREATE TABLE CODE
(
    ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    "value" VARCHAR(64) NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES "user" (ID)
);
CREATE UNIQUE INDEX UKEY_CODE_USER_ID ON CODE (USER_ID);
